- title: 'Member. Multimedia Subcomittee, Early Career Leadership Program. Genetics Society of America'
  description: '(2024-present) Create multimedia content (podcast, infographics, etc.) to communicate and disseminate current genetics research to a broad scientific audience'

- title: 'Founder & Graduate Student Representative. Office of Student Relations, Department of Biology. University of Rochester, NY'
  description: '(2023-present) Develop and execute resources, events, and lines of communication to increase undergraduate participation in biological research and department events'
  
- title: 'STEM Professional. Letters to a Pre-Scientist.'
  description: '(2022-present) Exchange letters with middle and high school students from low-income schools in order to demystify STEM career pathways and inspire students to pursue a future in STEM'
  
- title: 'Field Assistant. Braddock Bay Bird Observatory. Rochester, NY'
  description: '(2022-present) Assist with mist-netting, handling live birds, and bird banding. Educate visitors to the banding station on research goals and the trapping process'
  
- title: 'Co-instructor. Upward Bound. University of Rochester, NY'
  description: '(2023-2024) Created and co-led a hands-on workshop introducing the genetics of evolution to low-income/first-generation high school students from Rochester City School District.' 

- title: 'Founder & Member. Graduate Student Recruitment Committee. University of Rochester, NY'
  description: '(2022-2023) Planned and executed events surrounding new graduate student recruitment, including interview week and orientation'
  
- title: 'Dance Instructor. The Breakaway Swing Dance. Oakland, CA'
  description: '(2018-2020) Developed and implemented lessons for 50-person classes, mentored swing dancers of all ages and skill levels. Promoted and presented on the diverse history of jazz and swing dance in the United States'
