- title: 'Founder & Member. Graduate Student Recruitment Committee. University of Rochester, NY'
  description: '(2022-present) Plan and execute events surrounding new graduate student recruitment, including interview week and orientation'

- title: 'Field Assistant. Braddock Bay Bird Observatory. Rochester, NY'
  description: '(2022-present) Assist with mist-netting, handling live birds, and bird banding. Educate visitors to the banding station on research goals and the trapping process'

- title: 'Member. Diversity & Inclusion in Biological Sciences (DIBS). University of Rochester, NY'
  description: '(2021-present) Conduct climate surveys to foster communication and change regarding equity in the Biology department, discuss various topics surrounding diversity in science'
